version: "3"
services:
  bayztracker-db:
    image: postgres:latest
    container_name: "bayztracker-db"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  bayztracker-app:
    image: bayztracker-app
    container_name: bayztracker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 5432
    depends_on:
      - bayztracker-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bayztracker-db:5432/postgres?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

