# Spring Boot initialConfiguration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}

    initialization-mode: always
    schema: classpath:/schema.sql

app:
  jwt:
    expiration: 86400000
    secret: Mh47cEyENtjz9PCgS4wjPLEmgHZajM

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate.SQL: info

# Server initialConfiguration
server:
  port: 8080
